
/*
 */

#include <mach/iomux-mx6dl.h>

static iomux_v3_cfg_t mx6solo_ar6mxcs_pads[] = {
  /* CCM  */
  MX6DL_PAD_CSI0_MCLK__CCM_CLKO,

  /* AUDMUX */
  MX6DL_PAD_CSI0_DAT4__AUDMUX_AUD3_TXC,
  MX6DL_PAD_CSI0_DAT5__AUDMUX_AUD3_TXD,
  MX6DL_PAD_CSI0_DAT6__AUDMUX_AUD3_TXFS,
  MX6DL_PAD_CSI0_DAT7__AUDMUX_AUD3_RXD,
  MX6DL_PAD_SD1_DAT0__GPIO_1_16,		 /* SPK_DET */
  MX6DL_PAD_SD1_CLK__GPIO_1_20,			 /* MIC_DET */

  /* ENET */
  MX6DL_PAD_ENET_MDIO__ENET_MDIO,
  MX6DL_PAD_ENET_MDC__ENET_MDC,
  MX6DL_PAD_ENET_REF_CLK__ENET_TX_CLK,
  MX6DL_PAD_RGMII_TXC__ENET_RGMII_TXC,
  MX6DL_PAD_RGMII_TD0__ENET_RGMII_TD0,
  MX6DL_PAD_RGMII_TD1__ENET_RGMII_TD1,
  MX6DL_PAD_RGMII_TD2__ENET_RGMII_TD2,
  MX6DL_PAD_RGMII_TD3__ENET_RGMII_TD3,
  MX6DL_PAD_RGMII_TX_CTL__ENET_RGMII_TX_CTL,
  MX6DL_PAD_RGMII_RXC__ENET_RGMII_RXC,
  MX6DL_PAD_RGMII_RD0__ENET_RGMII_RD0,
  MX6DL_PAD_RGMII_RD1__ENET_RGMII_RD1,
  MX6DL_PAD_RGMII_RD2__ENET_RGMII_RD2,
  MX6DL_PAD_RGMII_RD3__ENET_RGMII_RD3,
  MX6DL_PAD_RGMII_RX_CTL__ENET_RGMII_RX_CTL,
  MX6DL_PAD_ENET_TX_EN__GPIO_1_28,   /* PHY_INT    */
  MX6DL_PAD_ENET_RXD0__GPIO_1_27, 	 /* PHY_RST    */

  /* USDHC 3 */
  MX6DL_PAD_SD3_CLK__USDHC3_CLK_50MHZ,
  MX6DL_PAD_SD3_CMD__USDHC3_CMD_50MHZ,
  MX6DL_PAD_SD3_DAT0__USDHC3_DAT0_50MHZ,
  MX6DL_PAD_SD3_DAT1__USDHC3_DAT1_50MHZ,
  MX6DL_PAD_SD3_DAT2__USDHC3_DAT2_50MHZ,
  MX6DL_PAD_SD3_DAT3__USDHC3_DAT3_50MHZ,
  MX6DL_PAD_SD3_DAT5__GPIO_7_0,      /* SD3_CD_B   */

  /* USDHC 4 */
  MX6DL_PAD_SD4_CLK__USDHC4_CLK_50MHZ,
  MX6DL_PAD_SD4_CMD__USDHC4_CMD_50MHZ,
  MX6DL_PAD_SD4_DAT0__USDHC4_DAT0_50MHZ,
  MX6DL_PAD_SD4_DAT1__USDHC4_DAT1_50MHZ,
  MX6DL_PAD_SD4_DAT2__USDHC4_DAT2_50MHZ,
  MX6DL_PAD_SD4_DAT3__USDHC4_DAT3_50MHZ,
  MX6DL_PAD_SD4_DAT4__USDHC4_DAT4_50MHZ,
  MX6DL_PAD_SD4_DAT5__USDHC4_DAT5_50MHZ,
  MX6DL_PAD_SD4_DAT6__USDHC4_DAT6_50MHZ,
  MX6DL_PAD_SD4_DAT7__USDHC4_DAT7_50MHZ,

  /* UART 1 */
  MX6DL_PAD_SD3_DAT6__UART1_RXD,
  MX6DL_PAD_SD3_DAT7__UART1_TXD,
  MX6DL_PAD_EIM_D19__UART1_CTS,
  MX6DL_PAD_EIM_D20__UART1_RTS,

  /* UART 4 -- console */
  MX6DL_PAD_KEY_ROW0__UART4_RXD,
  MX6DL_PAD_KEY_COL0__UART4_TXD,

	/* CAN bus */
	MX6DL_PAD_KEY_COL4__CAN2_TXCAN,
	MX6DL_PAD_KEY_ROW4__CAN2_RXCAN,
	MX6DL_PAD_GPIO_2__GPIO_1_2,				/* CAN_STBY */

  /* I2C1 */
  MX6DL_PAD_CSI0_DAT9__I2C1_SCL,
  MX6DL_PAD_CSI0_DAT8__I2C1_SDA,

  /* I2C2 */
  MX6DL_PAD_KEY_COL3__I2C2_SCL,
  MX6DL_PAD_KEY_ROW3__I2C2_SDA,

  /* I2C3 */
  MX6DL_PAD_GPIO_3__I2C3_SCL,
  MX6DL_PAD_GPIO_6__I2C3_SDA,

  /* WDOG 2 */
  MX6DL_PAD_SD1_DAT3__WDOG2_WDOG_RST_B_DEB,

  /* HDMI CEC */
  MX6DL_PAD_KEY_ROW2__HDMI_TX_CEC_LINE,

	/* USB OTG */
  MX6DL_PAD_GPIO_1__USBOTG_ID,       /* USB_OTG_ID */

	/* SPDIF */
  MX6DL_PAD_ENET_CRS_DV__SPDIF_SPDIF_EXTCLK,
  MX6DL_PAD_GPIO_8__SPDIF_SRCLK,

	/* PCIE */
  MX6DL_PAD_GPIO_9__GPIO_1_9,        /* PCIE_DIS_B */
  MX6DL_PAD_GPIO_16__GPIO_7_11,      /* PCIE_RST_B */

  /* GPIO1 */
  MX6DL_PAD_GPIO_0__GPIO_1_0,        /* SW_RST     */
  MX6DL_PAD_GPIO_4__GPIO_1_4,        /* VER_B0 */
  MX6DL_PAD_GPIO_5__GPIO_1_5,        /* VER_B1 */

  /* GPIO2 */
  MX6DL_PAD_NANDF_D0__GPIO_2_0,
  MX6DL_PAD_NANDF_D1__GPIO_2_1,
  MX6DL_PAD_NANDF_D2__GPIO_2_2,
  MX6DL_PAD_NANDF_D3__GPIO_2_3,
  MX6DL_PAD_NANDF_D4__GPIO_2_4,
  MX6DL_PAD_NANDF_D5__GPIO_2_5,
  MX6DL_PAD_NANDF_D6__GPIO_2_6,
  MX6DL_PAD_NANDF_D7__GPIO_2_7,

  /* GPIO4 */
  MX6DL_PAD_KEY_COL1__GPIO_4_8,			 /* L0_PWREN */
  MX6DL_PAD_KEY_ROW1__GPIO_4_9,			 /* BL0_PWREN */

  /* GPIO5 */

  /* GPIO6 */
  MX6DL_PAD_NANDF_CLE__GPIO_6_7,		 /* RTC_INT */
  MX6DL_PAD_NANDF_ALE__GPIO_6_8,		 /* CAP_TCH_INT0 */
  MX6DL_PAD_NANDF_WP_B__GPIO_6_9,		 /* GPIO_LED1 */
  MX6DL_PAD_NANDF_RB0__GPIO_6_10,		 /* GPIO_LED2 */

  /* GPIO7 */
  MX6DL_PAD_GPIO_18__GPIO_7_13,			 /* USB_RST */


#if 0
  /* BT */
  MX6DL_PAD_EIM_DA0__SRC_BT_CFG_0,
  MX6DL_PAD_EIM_DA1__SRC_BT_CFG_1,
  MX6DL_PAD_EIM_DA10__SRC_BT_CFG_10,
  MX6DL_PAD_EIM_DA11__SRC_BT_CFG_11,
  MX6DL_PAD_EIM_DA12__SRC_BT_CFG_12,
  MX6DL_PAD_EIM_DA13__SRC_BT_CFG_13,
  MX6DL_PAD_EIM_DA14__SRC_BT_CFG_14,
  MX6DL_PAD_EIM_DA15__SRC_BT_CFG_15,
  MX6DL_PAD_EIM_A16__SRC_BT_CFG_16,
  MX6DL_PAD_EIM_A17__SRC_BT_CFG_17,
  MX6DL_PAD_EIM_A18__SRC_BT_CFG_18,
  MX6DL_PAD_EIM_A19__SRC_BT_CFG_19,
  MX6DL_PAD_EIM_DA2__SRC_BT_CFG_2,
  MX6DL_PAD_EIM_A20__SRC_BT_CFG_20,
  MX6DL_PAD_EIM_A21__SRC_BT_CFG_21,
  MX6DL_PAD_EIM_A22__SRC_BT_CFG_22,
  MX6DL_PAD_EIM_A23__SRC_BT_CFG_23,
  MX6DL_PAD_EIM_A24__SRC_BT_CFG_24,
  MX6DL_PAD_EIM_WAIT__SRC_BT_CFG_25,
  MX6DL_PAD_EIM_LBA__SRC_BT_CFG_26,
  MX6DL_PAD_EIM_EB0__SRC_BT_CFG_27,
  MX6DL_PAD_EIM_EB1__SRC_BT_CFG_28,
  MX6DL_PAD_EIM_RW__SRC_BT_CFG_29,
  MX6DL_PAD_EIM_DA3__SRC_BT_CFG_3,
  MX6DL_PAD_EIM_EB2__SRC_BT_CFG_30,
  MX6DL_PAD_EIM_DA4__SRC_BT_CFG_4,
  MX6DL_PAD_EIM_DA5__SRC_BT_CFG_5,
  MX6DL_PAD_EIM_DA6__SRC_BT_CFG_6,
  MX6DL_PAD_EIM_DA7__SRC_BT_CFG_7,
  MX6DL_PAD_EIM_DA8__SRC_BT_CFG_8,
  MX6DL_PAD_EIM_DA9__SRC_BT_CFG_9,
#endif
 };

static iomux_v3_cfg_t mx6solo_ar6mxcs_hdmi_ddc_pads[] = {
	MX6DL_PAD_KEY_COL3__HDMI_TX_DDC_SCL, /* HDMI DDC SCL */
	MX6DL_PAD_KEY_ROW3__HDMI_TX_DDC_SDA, /* HDMI DDC SDA */
};

static iomux_v3_cfg_t mx6solo_ar6mxcs_i2c2_pads[] = {
	MX6DL_PAD_KEY_COL3__I2C2_SCL,	/* I2C2 SCL */
	MX6DL_PAD_KEY_ROW3__I2C2_SDA,	/* I2C2 SDA */
};
